name: DRPreter
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=23.0=pyhd8ed1ab_0
  - pytorch_geometric=2.2.0=pyhd8ed1ab_0
  - pip:
    - dgl==1.0.0
    - dgllife==0.3.1
    - openpyxl==3.1.0
    - pandas==1.5.3
    - rdkit==2022.9.4
    - seaborn==0.12.2