name: DRPreter
channels:
  - pytorch
  - pyg
  - defaults
dependencies:
  - pyg=2.2.0
  - python=3.10
  - pytorch=1.12.1=py3.10_cuda11.3_cudnn8.3.2_0
  - pip:
    - dgl==1.0.0
    - dgllife==0.3.1
    - openpyxl==3.1.1
    - pandas==1.5.3
    - rdkit==2022.9.4
    - seaborn==0.12.2
